print("Mufeena")
print("Paruthipra")
print("Maniyamkadu")
print("MCA")
print("MES Engineering College")
a=input("Enter your name:")
print(a)
color=input("what color is rose:")
print(color)
n=int(input("how many roses:"))
print(n)
price=float(input("Price of each rose:"))
print(price)
